POST http://localhost:3001/api/locales
Content-Type: application/json

{
    "nombre": "Test post",
    "direccion": "Calle nueva",
    "musica": "music",
    "url": "www.test.com",
    "consumicion": 7,
    "horario": "03:00",
    "userId": "645a2881417af83932e981eb"
}

###

DELETE http://localhost:3001/api/locales/64578e2c8008248bba6e852e

###

GET http://localhost:3001/api/locales


###

PUT http://localhost:3001/api/locales/64578e5e8008248bba6e8534
Content-Type: application/json

{
    "nombre": "Test update",
    "direccion": "Calle nueva",
    "musica": "music",
    "consumicion": 7,
    "horario": "21:00-02:00"
}
